import geocoder
import requests
import yaml
import random
import sys
from io import StringIO
from BASE_DATA import weather_api_key,llm
import urllib.parse
import json
from functools import lru_cache

degree_symbol = "\u00b0"

class MultilingualCityResolver:
    """Handle multilingual city name resolution using various APIs"""
    
    def __init__(self):
        self.geocoding_url = "http://api.openweathermap.org/geo/1.0/direct"
        
    @lru_cache(maxsize=128)
    def resolve_city_coordinates(self, city_name, limit=5):
        """
        Use OpenWeatherMap's Geocoding API to resolve city names in any language
        Returns list of possible matches with coordinates
        """
        try:
            params = {
                'q': city_name,
                'limit': limit,
                'appid': weather_api_key
            }
            
            response = requests.get(self.geocoding_url, params=params, timeout=10)
            response.raise_for_status()
            
            locations = response.json()
            return locations
            
        except Exception as e:
            print(f"Error in geocoding: {e}")
            return []
    
    def get_best_city_match(self, city_name):
        """
        Get the best matching city from geocoding results
        Returns tuple: (resolved_name, lat, lon) or (None, None, None)
        """
        locations = self.resolve_city_coordinates(city_name)
        
        if not locations:
            return None, None, None
            
        # Take the first (most relevant) result
        best_match = locations[0]
        
        return (
            best_match.get('name'),
            best_match.get('lat'),
            best_match.get('lon')
        )
    
    def get_alternative_matches(self, city_name, max_results=3):
        """Get multiple possible matches for ambiguous city names"""
        locations = self.resolve_city_coordinates(city_name)
        
        results = []
        for location in locations[:max_results]:
            city_info = {
                'name': location.get('name'),
                'country': location.get('country'),
                'state': location.get('state', ''),
                'lat': location.get('lat'),
                'lon': location.get('lon')
            }
            results.append(city_info)
            
        return results

def get_user_city(city_name=None):
    """Get city name either from parameter or user's IP location"""
    if city_name:
        return city_name
    try:
        location = geocoder.ip("me")
        return location.city if location.city else "City not found"
    except Exception as e:
        print(f"Error getting location: {e}")
        return None

def kelvin_to_celsius(kelvin):
    """Convert Kelvin to Celsius"""
    return kelvin - 273.15

def get_weather_by_coordinates(lat, lon, language="en"):
    """Get weather data using coordinates (more reliable for international cities)"""
    url = f"http://api.openweathermap.org/data/2.5/weather"
    params = {
        'lat': lat,
        'lon': lon,
        'appid': weather_api_key,
        'lang': language
    }
    
    try:
        response = requests.get(url, params=params, timeout=10)
        response.raise_for_status()
        return response.json()
    except Exception as e:
        raise Exception(f"Error fetching weather data: {e}")

def generate_weather_report_llm(weather_data, llm_client):
    prompt = f"""
    Create a friendly weather report:
    Location: {weather_data['location']}
    Temperature: {weather_data['temperature']}°C (feels like {weather_data['feels_like']}°C)
    Humidity: {weather_data['humidity']}%
    Wind Speed: {weather_data['wind_speed']} m/s
    Conditions: {weather_data['conditions']}
    
    Make it conversational and natural.
    """
    response = llm_client.invoke(prompt)

    return getattr(response, "content", str(response))


def get_weather(city_name=None, language="en", show_alternatives=False):
    """
    Get weather data for a city in specified language with multilingual support.
    Returns a conversational weather report generated by the LLM.
    """
    resolver = MultilingualCityResolver()
    input_city = get_user_city(city_name)
    if not input_city:
        return "Could not determine city"

    if show_alternatives:
        alternatives = resolver.get_alternative_matches(input_city)
        if len(alternatives) > 1:
            alt_text = "\n".join([
                f"  - {alt['name']}, {alt['country']}" + 
                (f" ({alt['state']})" if alt['state'] else "")
                for alt in alternatives
            ])
            return f"Multiple cities found for '{input_city}':\n{alt_text}\n\nPlease be more specific (e.g., include country/state)."
    
    resolved_name, lat, lon = resolver.get_best_city_match(input_city)
    
    if not resolved_name or lat is None or lon is None:
        return f"Could not find city: {input_city}. Please check the spelling or try a different format."
    
    try:
        data = get_weather_by_coordinates(lat, lon, language)
        temp_celsius = kelvin_to_celsius(data["main"]["temp"])
        feels_like_celsius = kelvin_to_celsius(data["main"]["feels_like"])
        humidity = data["main"]["humidity"]
        wind_speed = data["wind"]["speed"]
        description = data["weather"][0]["description"]
        country = data.get("sys", {}).get("country", "")
        location_display = f"{resolved_name}" + (f", {country}" if country else "")
        
        weather_data = {
            "location": location_display,
            "temperature": round(temp_celsius, 1),
            "feels_like": round(feels_like_celsius, 1),
            "humidity": humidity,
            "wind_speed": wind_speed,
            "conditions": description.title()
        }
        
        return generate_weather_report_llm(weather_data, llm)
        
    except Exception as e:
        return f"Error getting weather for {resolved_name}: {e}"


def search_cities(query, max_results=5):
    """Search for cities matching a query in any language"""
    resolver = MultilingualCityResolver()
    alternatives = resolver.get_alternative_matches(query, max_results)
    
    if not alternatives:
        return f"No cities found matching: {query}"
    
    result = f"Cities matching '{query}':\n"
    for i, alt in enumerate(alternatives, 1):
        location_str = f"{alt['name']}, {alt['country']}"
        if alt['state']:
            location_str += f" ({alt['state']})"
        result += f"{i}. {location_str}\n"
    
    return result.strip()